DEVX-2160: Added Self Balancing Clusters tutorial.
confluentinc/cp-demo pull request #363
Opened 2021-03-29 01:35 UTC by javabrett

### Description 

https://confluentinc.atlassian.net/browse/DEVX-2160
Follows from https://confluentinc.atlassian.net/browse/DEVX-2162

_What behavior does this PR change, and why?_

Adds tutorial for executing the Self-Balancing Clusters demo.

### Author Validation

_Describe the validation already done, or needs to be done, by the PR submitter._

- [X] Documentation -->
- [X] Run cp-demo -->
- [ ] jmx-monitoring-stacks

### Reviewer Tasks

_Describe the tasks/validation that the PR submitter is requesting to be done by the reviewer._

2021-04-05 20:13 UTC, Marcinthecloud approved these changes
Looks great! Thanks Brett.

2021-04-06 03:00 UTC, ybyzek reviewed
Thanks for adding to the docs @javabrett .

2021-04-06 03:00 UTC, ybyzek commented on docs/on-prem.rst
> +#. Monitor the progress of replica-reassignment from the failed broker, which will eventually reduce the under-replicated partitions in the cluster back to zero.  To track completion of self-healing,
Tell the user what they should expect in the output of these scripts.

2021-04-06 03:00 UTC, ybyzek commented on docs/on-prem.rst
> +   You can check the status using the following scripts to read the broker logs:
Tell the user what they should expect in the output of these scripts.

2021-04-06 15:16 UTC, arodoni reviewed
Will approve when all @ybyzek 's comments are addressed.

2021-04-14 05:43 UTC, javabrett commented on docs/on-prem.rst
> +#. Open Control Center at http://localhost:9021 and navigate to Brokers.  The Self-balancing panel will show 1 in-progress task.
Added 3, may need review and editing.

2021-04-14 06:46 UTC, javabrett commented on docs/on-prem.rst
> +
Done.

2021-04-14 12:47 UTC, ybyzek requested changes
@javabrett I created a PR to merge into this PR --> https://github.com/confluentinc/cp-demo/pull/366 (lots of minor docs tweaks and a screenshot improvement).  I combed it over while I ran through the steps.  It would be great if you could please review and merge it in if you agree with the changes.

Also, in my environment, the `add-broker` was unsuccessful.  It failed to rebalance.  I think it's important to investigate and understand why -- functional issue or hardware resource issue?  If it failed in my environment (my laptop is relatively well spec'd), it will fail in others.

<img width="438" alt="Screen Shot 2021-04-14 at 08 34 08 AM" src="https://user-images.githubusercontent.com/12448600/114712337-fa019a00-9cfd-11eb-9948-9ac15c5c613a.png">

2021-04-14 14:51 UTC, ybyzek commented
@javabrett a second run-thru worked.  One difference between the two runs:

- run that failed: did not wait initial 15 minutes
- run that passed: did wait initial 15 minutes

I don't know if the initial 15 minute wait is the reason, but I did augment my PR to mention waiting

2021-04-15 00:16 UTC, ybyzek commented
Cool, thanks for merging.  I triggered a new docs build (https://github.com/confluentinc/docs-platform/pull/578) -- let's confirm docs builds ok and then I'll approve this PR.

2021-04-15 20:01 UTC, ybyzek approved these changes
@javabrett the docs PR passes.  So this PR LGTM and ready to ship.  Wonderful work, thank you!

2021-04-15 22:52 UTC, merged